from datetime import datetime
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from database import get_db
from models import WorkLog
from schemas import WorkLogCreate

router = APIRouter(prefix="/eligibility", tags=["Eligibility"])


@router.post("/log")
def add_log(data: WorkLogCreate, db: Session = Depends(get_db)):
    already = (
        db.query(WorkLog)
        .filter(
            WorkLog.phone == data.phone,
            WorkLog.platform == data.platform,
            WorkLog.work_date == data.work_date,
        )
        .first()
    )
    if already:
        if data.has_evidence and not already.has_evidence:
            already.has_evidence = True
        already.earnings = data.earnings
        db.commit()
        return {"message": "This day's record was updated"}

    log = WorkLog(
        phone=data.phone,
        platform=data.platform,
        work_date=data.work_date,
        has_evidence=data.has_evidence,
        earnings=data.earnings,
    )
    db.add(log)
    db.commit()
    return {"message": "Day saved successfully"}


@router.get("/{phone}")
def check_eligibility(phone: str, db: Session = Depends(get_db)):
    logs = db.query(WorkLog).filter(WorkLog.phone == phone).all()

    days_per_platform = {}
    earnings_per_platform = {}
    for log in logs:
        days_per_platform[log.platform] = days_per_platform.get(log.platform, 0) + 1
        earnings_per_platform[log.platform] = earnings_per_platform.get(log.platform, 0) + log.earnings

    total_days = len({log.work_date for log in logs})
    total_earnings = sum(log.earnings for log in logs)
    best_single = max(days_per_platform.values(), default=0)
    evidence_count = len({log.work_date for log in logs if log.has_evidence})

    avg_daily_earning = round(total_earnings / total_days, 2) if total_days > 0 else 0

    if best_single >= 90:
        eligible = True
        reason = "You have completed 90 days on a single platform"
    elif len(days_per_platform) > 1 and total_days >= 120:
        eligible = True
        reason = "You have completed 120 days across multiple platforms"
    else:
        eligible = False
        reason = "You have not yet completed the required eligibility period"

    return {
        "phone": phone,
        "days_per_platform": days_per_platform,
        "earnings_per_platform": earnings_per_platform,
        "total_days": total_days,
        "total_earnings": total_earnings,
        "average_daily_earning": avg_daily_earning,
        "evidence_backed_days": evidence_count,
        "self_declared_days": total_days - evidence_count,
        "eligible": eligible,
        "reason": reason,
        "days_left_single_platform": max(0, 90 - best_single),
        "days_left_multi_platform": max(0, 120 - total_days),
    }


@router.get("/{phone}/certificate")
def get_certificate(phone: str, db: Session = Depends(get_db)):
    logs = db.query(WorkLog).filter(WorkLog.phone == phone).all()

    if not logs:
        return {"certificate_text": "No work records found for this phone number."}

    days_per_platform = {}
    earnings_per_platform = {}
    for log in logs:
        days_per_platform[log.platform] = days_per_platform.get(log.platform, 0) + 1
        earnings_per_platform[log.platform] = earnings_per_platform.get(log.platform, 0) + log.earnings

    total_days = len({log.work_date for log in logs})
    total_earnings = sum(log.earnings for log in logs)
    evidence_count = len({log.work_date for log in logs if log.has_evidence})
    best_single = max(days_per_platform.values(), default=0)

    eligible = best_single >= 90 or (len(days_per_platform) > 1 and total_days >= 120)

    platform_lines = "\n".join(
        f"  - {name}: {days} days, Rs.{earnings_per_platform[name]:,.2f} earned"
        for name, days in days_per_platform.items()
    )

    certificate = f"""WORK HISTORY CERTIFICATE
Generated by NyayaGig Navigator

Phone Number: {phone}
Date Generated: {datetime.now().strftime('%d %B %Y')}

SUMMARY
Total Working Days (unique): {total_days}
Total Earnings: Rs.{total_earnings:,.2f}
Evidence-Backed Days: {evidence_count} out of {total_days}
Social Security Eligibility Status: {"ELIGIBLE" if eligible else "NOT YET ELIGIBLE"}

PLATFORM-WISE BREAKDOWN
{platform_lines}

DECLARATION
This certificate is self-generated based on records logged by the worker
on the NyayaGig Navigator platform. Days marked as evidence-backed are
supported by uploaded screenshots. This document may be used to support
applications for social security benefits under the Code on Social
Security, 2020, or state-level gig worker welfare schemes.

Generated via NyayaGig Navigator
"""

    return {"certificate_text": certificate}